export interface Char{
    _id:number,
    alignment:string,
    allies:string[],
    enemies:string[],
    films:string[],
    imageUrl:string,
    name:string,
    parkAttractions:string[],
    shortFilms:string[],
    sourceUrl:string,
    tvShows:string[],
    url:string,
    videoGames:string[],
}
